// Suggested skill chips shown as one-click chips below the skills input.
// Students can also type their own; this is just a friendly starter set.
export const SKILL_SUGGESTIONS = [
  "React",
  "TypeScript",
  "Tailwind",
  "Node.js",
  "Python",
  "Flutter",
  "Figma",
  "Illustrator",
  "Photoshop",
  "Logo Design",
  "Branding",
  "Video Editing",
  "Premiere Pro",
  "After Effects",
  "Reels",
  "TikTok",
  "Content Writing",
  "Copywriting",
  "Technical Writing",
  "SEO",
  "Translation",
  "Urdu",
  "English",
  "Tutoring",
  "Mathematics",
  "O-Level",
  "A-Level",
  "Physics",
  "Excel",
  "Power BI",
  "Data Entry",
  "Research",
  "Survey Design",
  "Photography",
  "Lightroom",
  "Audio Editing",
  "Machine Learning",
  "Data Analysis",
  "Shopify",
  "Liquid",
  "WordPress",
  "Canva",
];

export const GIG_CATEGORIES = [
  "Web Dev",
  "Mobile Dev",
  "Graphic Design",
  "Tutoring",
  "Content Writing",
  "Translation",
  "Data Entry",
  "Data Science",
  "Social Media",
  "Video Editing",
  "Photography",
  "Research",
  "Other",
];
